SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM TABELA_de_PRODUTOS
GROUP BY EMBALAGEM;

#USANDO SUB-CONSULTA
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM TABELA_de_PRODUTOS
GROUP BY EMBALAGEM) X WHERE X.MAIOR_PRECO >= 10;

#após criação da view podemos consultar diretamente 
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM
(vw_maiores_embalagens) X WHERE X.MAIOR_PRECO >= 10;
