CREATE table tbCliente
(CPF varchar(11),
NOME varchar(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 varchar(150),
BAIRRO varchar(50),
CIDADE varchar(50),
ESTADO varchar(50),
CEP varchar(8),
IDADE SMALLINT,
SEXO VARCHAR (1), 
LIMITE_CREDITO float,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1))