--criando novo Banco de Dados:
CREATE DATABASE `NOME DO BANCO DE DADOS`;
        ou
CREATE SCHEMA `NOME DO BANCO DE DADOS`;

--Apagando Banco de Dados:
DROP DATABASE `NOME DO BANCO DE DADOS`;
--        ou
DROP SCHEMA `NOME DO BANCO DE DADOS`;
--        ou
--Clicar com botão direito do mouse onde estao
        -- as listas dos bancos de dados em cima do nome do db que quer apagar
                --e clicar em 'DROP SCHEMA...'

--Selecionar  uma tabela (CITY) dentro de um banco de Dados(CLICAR EM CIMA E O DB SELECIONADO FICARÁ EM NEGRITO):
SELECT * FROM CITY


// = -- (comentar linha no SQL)